### ISSUE TITLE
Invalid date with date format = 'dd/mm/yyyy'

### ISSUE THREAD

**Issue by Adista9** [shogogan/racoon-lib#1]
When you fill a date with the date format = 'dd/mm/yyyy', and continue to fill till max numbers, there is an invalid date error. You must check if it is a valid date before updating model.

Something like this (did not tried):
```
if (this.value.length === this.mask.length && isDate(this.value)) {
  const date = this.host.parseValueFromString(this.value);
  this.host.updateModel(date);
}
```

**Comment by shogogan** [comment]
was looking through the primeng calendar doc, and these are the options:

```
d - day of month (no leading zero)
dd - day of month (two digit)
o - day of the year (no leading zeros)
oo - day of the year (three digit)
D - day name short
DD - day name long
m - month of year (no leading zero)
mm - month of year (two digit)
M - month name short
MM - month name long
y - year (two digit)
yy - year (four digit)
@ - Unix timestamp (ms since 01/01/1970)
! - Windows ticks (100ns since 01/01/0001)
'...' - literal text
'' - single quote
anything else - literal text
```

this lib still doesn't support all the formats, but for your case the correct date format should be `dd/mm/yy`

**Comment by shogogan** [comment]
will fix the readme later today, to be clear what date format does it support, but if you still get errors with the date format that i sent, then i'll lookup to fix it 🎩

**Comment by Adista9** [comment]
Yeah sorry, i wanted to say 'date format = dd/mm/yy'.

**Comment by shogogan** [comment]
Strange, will lookup what is happening

**Comment by shogogan** [comment]
oh, found out what is wrong, my bad, forgot the validation. fixed it on 0.0.6 🎩

**Comment by Adista9** [comment]
Did you try?

**Comment by shogogan** [comment]
Sorry for forgetting to test (this was pretty bad by my part) but was on a hurry here, if there is any problem just open an issue or a PR 👍
